### ISSUE TITLE
Not working with Thunderbird 115.0b4

### ISSUE THREAD

**Issue by michalwoz** [lkosson/full-address-column#14] opened 2023-06-24 00:32 UTC
Hi,

May I ask to check if there is significant change that prevent from working with 115.0b4?

**Comment by lkosson** [comment] 2023-06-25 14:20
Hi. It seems Mozilla has completely redesigned (yet again) internals of message pane in Thunderbird 114, along with some other hideous UI changes. If those changes make it to ESR/release channel, the addon will be officially dead.

**Comment by lkosson** [comment] 2023-06-30 07:12
Issues to track:

https://phabricator.services.mozilla.com/D179632
https://bugzilla.mozilla.org/show_bug.cgi?id=1817682
https://bugzilla.mozilla.org/show_bug.cgi?id=1615801

Discussions:
https://thunderbird.topicbox.com/groups/addons/Te5f62259df8c0c74
https://thunderbird.topicbox.com/groups/addons/T3c6ef3b787f59129

**Comment by lkosson** [comment] 2023-07-12 16:50
No workarounds or alternatives at this point. I don't think it's possible to reliably add custom columns until https://phabricator.services.mozilla.com/D179632 gets merged.

**Comment by lsr1** [comment] 2023-09-30 22:26
The fact that an EMAIL client has no possibility to display the sender EMAIL address (w/o a third party tool) is so infuriating. 

I wonder who makes those decisions.

**Comment by lones** [comment] 2023-10-02 08:59
Very sorry to see this is no longer possible. To see the email address of the sender is essential.

**Comment by gss0** [comment] 2023-10-04 07:40
https://connect.mozilla.org/t5/ideas/new-column-for-e-mail-adress-of-sender/idi-p/38300

**Comment by olfMombach** [comment] 2023-10-06 16:10
> The fact that an EMAIL client has no possibility to display the sender EMAIL address (w/o a third party tool) is so infuriating.
> 
> I wonder who makes those decisions.

I know right? And how come so few people are talking about this? Also I can't wrap my head around how this decision was taken in the design process. It's such a vital part for visually scanning mails for malicous intent, I'd regard it as an essential security feature. Makes me wonder if someone on the board came from a spammail provider.

**Comment by shalak** [comment] 2023-10-08 22:40
From what I understand on 2023-09-16 John Bieling picked this task to be fixed, so there's hope what this will be fixed soon, right? Right?

**Comment by benintech** [comment] 2023-10-11 12:47
Nothing new to add, I'm just another unhappy TB user here, missing the ability to see the sender's email address. I switched back to a previous version of TB, with full address column extension, until this feature works again one way or another in TB115+. I hope with all those unhappy TB users something will be done about it.

**Comment by milenamilka755** [comment] 2023-10-17 18:46
Temporary solution:
Downgrade to 102 version
https://www.companionlink.com/support/kb/How_to_downgrade_ThunderBird_Supernova_115_to_Regular_Thunderbird_102_Email

**Comment by dracken** [comment] 2023-11-09 16:07
> Temporary solution: Downgrade to 102 version https://www.companionlink.com/support/kb/How_to_downgrade_ThunderBird_Supernova_115_to_Regular_Thunderbird_102_Email

Can confirm following the steps in this link to revert back to v102 does work and will allow usage of incompatible plugins with v115.

**Comment by lkosson** [comment] 2023-12-01 06:12
Also worth tracking:
https://bugzilla.mozilla.org/show_bug.cgi?id=243258

**Comment by jeppe-at-acapire-se** [comment] 2023-12-09 14:38
Ping! Just to make sure this isn't forgotten.

**Comment by olfMombach** [comment] 2023-12-09 18:26
> Ping! Just to make sure this isn't forgotten.

Why would they forget about it? They were literally killed off completely by Mozilla's TB Update

**Comment by GoldMath** [comment] 2023-12-23 20:29
It's still beyond me that mail clients don't have that native, it's the best against phishing attacks as you can quickly check source instead of these fake names... I'm really looking for an alternative now; thanks for your work sadly shutdown.

**Comment by lkosson** [comment] 2023-12-25 09:12
Good news, everyone! Thanks to [the new API](https://bugzilla.mozilla.org/show_bug.cgi?id=1615801) included in [this daily build](https://treeherder.mozilla.org/jobs?repo=try-comm-central&revision=cb5dc120dc7d15015e30ce05e8864e59f4caf674), the add-on is working again. I'll upload the updated version as soon as new TB version is released.

**Comment by Zwiebelring2000** [comment] 2024-01-19 10:00
Is there a release date?

**Comment by lkosson** [comment] 2024-01-19 10:03
No idea.

**Comment by CEWebDesign** [comment] 2024-01-21 07:41
Next Thunderbird release 115.7 should be January 23: 
[https://wiki.mozilla.org/Releases](url)
"Thunderbird approximately (i.e. not strictly) follows the **ESR schedule** listed there."
[https://whattrainisitnow.com/calendar/](url)

**Comment by lkosson** [comment] 2024-01-21 11:15
Required changes have not been merged into neither Daily nor Beta Thunderbird. I don't expect them to be included in a proper release any time soon.

**Comment by aspx1981** [comment] 2024-01-28 12:37
Hello, sorry I don't understand, I updated Thunderbird, now how can I install the new version with the new API ?

**Comment by lkosson** [comment] 2024-01-29 05:53
You can't. It's not yet released.

**Comment by ivan-paleo** [comment] 2024-02-07 09:06
So it won't work with the newly released 115.7.0?

**Comment by lkosson** [comment] 2024-02-07 09:10
No, it won't.

**Comment by Martin511** [comment] 2024-02-21 14:42
Maybe it will work with the new 115.8.0?
"Asking for a friend"

**Comment by lkosson** [comment] 2024-02-21 19:34
No idea. As far as I can tell, we're currently waiting for [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1615801) and [this changeset](https://phabricator.services.mozilla.com/D196693).

**Comment by doodhout** [comment] 2024-02-23 07:56
One of the latest comments in the linked issue states the following:

> Once it reached beta on the 19th, add-on developers can adjust their add-ons and test custom column support for their add-ons for Thunderbird Beta.

That means you should be able to test this add-on in the Thunderbird Beta starting from 2024-02-19.

**If** I find a quick way to install TB Beta alongside TB Stable on my linux installation, I might test this myself and report back.

**Comment by lkosson** [comment] 2024-02-23 08:11
I currently have side-by-side versions 102.15.1 (prev release), 115.8.0 (release), 124.0b1 (beta from 2024-02-19) and 125.0a1 (daily from 2024-02-22). None of those versions have this API available. The only version with support for custom columns was the one I've linked to in comment from 2023-12-23.

**Comment by Martin511** [comment] 2024-03-01 19:57
👉🏻 https://bugzilla.mozilla.org/show_bug.cgi?id=1615801#c19

**Comment by Martin511** [comment] 2024-03-21 23:46
Are there any news on this?

**Comment by lkosson** [comment] 2024-03-22 05:47
Nope. Just some activity [here](https://phabricator.services.mozilla.com/D196693) yesterday.

**Comment by MilesTeg81** [comment] 2024-03-30 10:27
> As a workaround, I enabled sender full address in the message (right) pane as well as all the extra headers. See my settings below on Thunderbird v115.6: ![Screenshot 2023-12-24 000110](https://private-user-images.githubusercontent.com/7840350/292647338-320eb7dd-1826-472e-8a4e-b2f56e9daf2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3OTM4NjQsIm5iZiI6MTcxMTc5MzU2NCwicGF0aCI6Ii83ODQwMzUwLzI5MjY0NzMzOC0zMjBlYjdkZC0xODI2LTQ3MmUtOGE0ZS1iMmY1NmU5ZGFmMmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMzBUMTAxMjQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjEwNTNiZjdiYzI1NTIwNWQyNWE5M2VjNzg4ZmMxZTYwZDc0ZmU0YWY0NmRjZTFiNGMxZDhiYzIzMzFkMmJlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eJIW9Az_wbYQuppLNUGvC6mXXeH9RN7JDYoRqkoCNiQ)
> 
> This helps me identify spoofed sender addresses and also to identify to which of my aliases they sent by quickly scrolling a bit down.
>   
[...]

wow, I completely missed this setting! thx a lot!! 

This (combined with DKIM verifier) already makes a huge difference! (Though I still can't wait for a working column option...)

---------

btw. Apart from the mentioned **bugzilla**, it's still possible to **VOTE** here:

- https://connect.mozilla.org/t5/ideas/new-column-for-e-mail-address-of-sender/idi-p/38300
- https://connect.mozilla.org/t5/ideas/apply-the-betterbird-patches-to-mozilla-thunderbird/idi-p/32404

I know, current state: "we are nearly there".  But that was also the case 20 years ago... :/

**Comment by pstein** [comment] 2024-04-10 14:58
> > As a workaround, I enabled sender full address in the message (right) pane as well as all the extra headers. See my settings below on Thunderbird v115.6: ![Screenshot 2023-12-24 000110](https://private-user-images.githubusercontent.com/7840350/292647338-320eb7dd-1826-472e-8a4e-b2f56e9daf2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3OTM4NjQsIm5iZiI6MTcxMTc5MzU2NCwicGF0aCI6Ii83ODQwMzUwLzI5MjY0NzMzOC0zMjBlYjdkZC0xODI2LTQ3MmUtOGE0ZS1iMmY1NmU5ZGFmMmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMzBUMTAxMjQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjEwNTNiZjdiYzI1NTIwNWQyNWE5M2VjNzg4ZmMxZTYwZDc0ZmU0YWY0NmRjZTFiNGMxZDhiYzIzMzFkMmJlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eJIW9Az_wbYQuppLNUGvC6mXXeH9RN7JDYoRqkoCNiQ)
> > This helps me identify spoofed sender addresses and also to identify to which of my aliases they sent by quickly scrolling a bit down.
> 

Cannot view your screenshot since it seems to be private.
Can you add it here publicly?
Where can I add this option?

**Comment by lkosson** [comment] 2024-05-02 15:19
As of Thunderbird 115.10.0, internal API to manipulate columns is available ([details here](https://bugzilla.mozilla.org/show_bug.cgi?id=1817682)). However, public API (available to normal add-ons) is still missing and - as per [recent comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1615801) - there even is no roadmap to release it.

I have published new version of Full Address Column - it's awaiting a review and should be available soon. It works with Thunderbird 115.10.0, but uses _experimental API_. This means the add-on is unrestricted and requires full permissions. Decide on your own if you trust it.

Also, on Thunderbird Daily (127, 2024-05-02) there is now native option to see raw Email in Correspondents/Sender/Recipient column.

New version (1.1.0) does not work with Thunderbird 102 - if you still use it, stay on version 1.0.4 from last year.

**Comment by lkosson** [comment] 2024-05-02 20:20
It is still awaiting a review at https://addons.thunderbird.net/ - usually it takes between a few minutes and a few days.

I can't upload .zip or .xpi to github - if you wish to install the add-on manually, zip all the files in `src` directory, change the extension to .xpi and use "Install add-on from file" in TB.

**Comment by Martin511** [comment] 2024-05-08 15:10
This is working so far - thank you for updating!
In my case the function to sort the column @sender does not work. Ist this bug known?

**Comment by lkosson** [comment] 2024-05-08 18:01
I have just fixed sorting - version 1.1.2 awaits review.

**Comment by olavsu1** [comment] 2024-05-17 07:37
At first startup it don't load colums correctly. Closing and reopening the Thunderbird window helps until next time.
Because after a long pause when starting thunderbird the columns are messed up again. Columns title and content do not match.  Thanks.

**Comment by sebma** [comment] 2024-05-30 18:21
> I have just fixed sorting - version 1.1.2 awaits review.

Hi, I could not install on Thunderbird v115.9.0.

After updating the thunderbird ubuntu package (upto v115.11.0), I was able to install the extension :smile:

**Comment by dom6770** [comment] 2024-06-24 08:58
> At first startup it don't load colums correctly. Closing and reopening the Thunderbird window helps until next time. Because after a long pause when starting thunderbird the columns are messed up again. Columns title and content do not match. Thanks.

I have the same issue on my personal Thunderbird profile, though not on my work profile, which is odd. When I open Thunderbird the columns headers are in the correct order, but the actual content of the mail is all over the place. When I deactivate the extension, this bug disappears. Sometimes I need to reopen Thunderbird up to 10 times until it's normal again.

Should we open a issue for that? Next time it happens I can make a video.

**Comment by lkosson** [comment] 2024-06-24 10:09
I might have seen this behavior once in Beta, but not ever since. Without a reliable way to reproduce it, I doubt I can do anything about it, even with a video. When it does reoccur, please check console (CTRL-SHIFT-J) for anything interesting.

You can open a new issue to keep things clean and on-topic in this one.

**Comment by lkosson** [comment] 2024-07-28 12:56
Closing this a main issue regarding compatibility with 115 is resolved.

For problem with corrupted column data, follow #24 and https://bugzilla.mozilla.org/show_bug.cgi?id=1909621

**Closed by lkosson** 2024-07-28 12:56 UTC
